### ISSUE TITLE
incorrect result

### ISSUE THREAD

**Issue by SSANSH** [rouanw/npm-audit-helper#2]
with following json:
`
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
  },
  "dependencies": {
    "axios": "^0.17.0",
    "elasticsearch": "^13.3.1"
  },
  "devDependencies": {
    "npm-audit-helper": "^2.3.17"
  }
}
`
when I ran command:
 npm audit --registry https://registry.npmjs.org/ --json | node_modules/.bin/npm-audit-helper --prod-only
I have the following report
`
                      === npm audit security report ===                        
                                                                                
# Run  npm install elasticsearch@16.1.1  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elasticsearch                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elasticsearch > lodash                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/782                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elasticsearch                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elasticsearch > lodash                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/577                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

found 3 vulnerabilities (1 low, 2 moderate) in 39 scanned packages
  2 vulnerabilities require semver-major dependency updates.

=== A little bit of help ===

Where to start:

- run `npm audit fix` to automatically fix 1 issues. These should all be non-breaking upgrades, so don't stress.

- Resolve the 1 moderate severity issues above and run this command again to move to the next severity.
`
axios should be displayed no?

if I change dependencies like that:

`
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
  },
  "dependencies": {
  },
  "devDependencies": {
    "axios": "^0.17.0",
    "elasticsearch": "^13.3.1",
    "npm-audit-helper": "^2.3.17"
  }
}
`
I have the same report even if my dependencies are on dev, should be hide due to prod-only parameter no?

**Comment by rouanw** [comment]
Hi @SSANSH and thanks for reporting! Sorry it's taken me so long to take a look.

I think the problem you're seeing here is because `npm audit` takes both the `package.json` and the `package-lock.json` into account. If I:

- Use the first `package.json`
- `npm install`
- `npm audit --registry https://registry.npmjs.org/ --json | node_modules/.bin/npm-audit-helper --prod-only`
- Change `package.json` as you have
- `npm audit --registry https://registry.npmjs.org/ --json | node_modules/.bin/npm-audit-helper --prod-only`

I get the same results as you, but if I run `npm install` after changing the `package.json` I get 0 vulnerabilities as expected. In other words, please try:

- Use the first `package.json`
- `npm install`
- `npm audit --registry https://registry.npmjs.org/ --json | node_modules/.bin/npm-audit-helper --prod-only`
- Change `package.json` as you have
- `npm install` <----- this is the difference 😸 
- `npm audit --registry https://registry.npmjs.org/ --json | node_modules/.bin/npm-audit-helper --prod-only`

and let me know if you still see the issue.
